// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject[]>}
 */
export async function LoadCountries() {
	// BEGIN USER CODE
	const res = await fetch('https://restcountries.com/v3.1/all')
	const json = await res.json()
	const countries = Promise.all(json.map(async data => {
		const country = await new Promise((callback, error) => {
			mx.data.create({ entity: "Countries.Country", callback, error })
		})
		country.set("Name", data.name.common)
		if (data.capital) country.set("Capital", data.capital[0])
		country.set("Flag", data.flag)
		return country
	}))
	console.info(countries)
	return countries
	// END USER CODE
}
